const GET_TODOS = 'GET_TODOS'
const ADD_TODO = 'ADD_TODO'
const DELETE_TODO = 'DELETE_TODO'
const DELETE_TODOS = 'DELETE_TODOS'
const EDITING_TODO = 'EDITING_TODO'
const UPDATE_TODO = 'UPDATE_TODO'
const PRIORITY_TODO = 'PRIORITY_TODO'
const TOGGLE_TODO = 'TOGGLE_TODO'
const CHANGE_FILTER = 'CHANGE_FILTER'

export {
  GET_TODOS,
  ADD_TODO,
  DELETE_TODO,
  DELETE_TODOS,
  EDITING_TODO,
  UPDATE_TODO,
  PRIORITY_TODO,
  TOGGLE_TODO,
  CHANGE_FILTER,
}
