const GET_USERS = 'GET_USERS'
const CREATE_USER = 'CREATE_USER'
const GET_USER = 'GET_USER'
const DELETE_USER = 'DELETE_USER'
const LOADING_START = 'LOADING_START'
const LOADING_END = 'LOADING_END'

export {
  GET_USERS,
  CREATE_USER,
  GET_USER,
  DELETE_USER,
  LOADING_START,
  LOADING_END,
}
